### ISSUE TITLE
Error when executed from Command prompt

### ISSUE THREAD

**Issue by hdsouza** [muthu-kc/lendingclub-php-script#1]
Hi Muthu, 
Thanks for  the php code.

When running from command prompt, I have tried PHP version 5.6.32-nts-Win32-VC11-x86 as well as 7.1.11-Win32-VC14-x86 and both give me an error "**Call to undefined function curl_init()**". 
If I place the same PHP file on my host and run it from a browser it works fine.
Any ideas why it does not work from Command prompt.
<img src = "https://i.imgur.com/BNtQqV4.jpg">

Thanks
Hil

**Comment by adiv-phpian** [comment]
Hi, Looks like curl not installed or enabled for cli. You have enable curl on command line in order to use it. 
Thanks.

**Comment by hdsouza** [comment]
Thanks Muthu. 
I managed to enable it in php.ini with extension=php_curl.dll but this time I get "Use of undefined constant DEBUG_LENDING_API".

<img src = "https://i.imgur.com/hTaT5L9.jpg">
Thanks

**Comment by adiv-phpian** [comment]
Make sure you didn't commented following line on index.php file

  /*** set false to receive only datas ***/
  define("DEBUG_LENDING_API", false);


If you want to enable debugging, set value from false into true.

**Comment by hdsouza** [comment]
Hi Muthu, 
You are right. I did not have the line. I was probably using an earlier version of the script. I created the PHP file again and this time the error is gone. 
Although when I try to get anything  (For example get_Balance or  get_notes) it returns nothing.
I have attached a copy of the php.ini and  index.php I am using.
[index.php](https://github.com/muthu-kc/lendingclub-php-script/files/1464778/index.txt)
[php.ini](https://github.com/muthu-kc/lendingclub-php-script/files/1464779/php.txt)

Again I am executing PHP from a windows Command line (Elevated as well as non-elevated). 
OS = Windows 10
I have tried both versions of PHP (PHP 7.1.11 and PHP 5.6.32)

Also if it will help I set define("DEBUG_LENDING_API", enable); and here is the output:
[log.txt](https://github.com/muthu-kc/lendingclub-php-script/files/1464826/log.txt)

Thanks

**Comment by adiv-phpian** [comment]
define("DEBUG_LENDING_API", true);

Put the above line and make sure your lending API credentials are right.
Still if you can't get output, send me credentials of your server, I will
debug the script. Because on my environment I will not get the same error.

Keep coding... never give up.

**Comment by hdsouza** [comment]
Hi Muthu,
i added define("DEBUG_LENDING_API", true); and here is the output
[log.txt](https://github.com/muthu-kc/lendingclub-php-script/files/1464929/log.txt)
Also I am not running the  script from a server. As mentioned  earlier I am running it from Windows 10 system via a command prompt.
If you run your PHP file from a windows command prompt you will see what i mean.
Could it be that JSON needs to be enabled/configured in PHP?
Thanks for your help
Hil

**Comment by adiv-phpian** [comment]
Sorry, I don't have windows on my end. You have to debug it on your end.
the log doesn't have much data. Make sure your API credentials and account
numbers are correct.

**Comment by hdsouza** [comment]
Hi Muthu,
I got it to work by placing the PHP file on my HOST.
It shows the account balance as well as the notes in my account crrectly.

But If I try to buy a note I get "Internal Server Error 1510609349610"
Does the script work on the  Secondary Market?

For example lets say I were to buy this note from the secondary market. 
https://www.lendingclub.com/foliofn/browseNotesLoanPerf.action?showfoliofn=true&loan_id=79154140&order_id=115222867&note_id=129717636

Here is the PHP file I am using. 

Thanks
Hil

**Comment by adiv-phpian** [comment]
You have to figure out this on your end. Thank you.

**Comment by hdsouza** [comment]
All I was asking was is it working for the secondary market.
If it does not work anymore, just say so. You dont need to be rude !!!!

**Comment by muthu-kc** [comment]
Hi, I don't know much about lending api. I just created this script for one
of my client before one year. If its working, use it. If it doesn't you may
need some other script.

Thank you.

**Comment by hdsouza** [comment]
Thats cool. Would you be interested in doing it as a project. 
If interested you could email (hdsouza @ yahoo) me cost or post here.
